version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    volumes:
      - $PWD:/etc/loki
    command:
      -config.file=/etc/loki/loki.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:make-images-static-26a87c9
    volumes:
      - $PWD:/etc/promtail
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - $PWD:/etc/prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
    networks:
      - loki

  loki_exporter:
    image: ricoberger/loki_exporter
    ports:
      - "9524:9524"
    volumes:
      - $PWD:/etc/loki_exporter
    command:
      -config.file=/etc/loki_exporter/loki_exporter.yml
    networks:
      - loki
